module.exports = {
    wm11111: {
        id: 1,
        image: '/res-img/item1.png',
        category: 'Collectibles',
        name: 'Digital art piece',
        current_bid: 2345,
        highest_bid: 0.005,
        available: true,
        time: 63019,
        ended: '30/05/2021',
        owner: 'Wolfram'
    },
    wm11112: {
        id: 2,
        image: '/res-img/item2.png',
        category: 'Collectibles',
        name: 'Digital art piece',
        current_bid: 2345,
        highest_bid: 0.005,
        available: true,
        time: 63019,
        ended: '',
        owner: 'Wolfram'
    },
    wm11113: {
        id: 3,
        image: '/res-img/item3.png',
        category: 'Collectibles',
        name: 'Digital art piece',
        current_bid: 2345,
        highest_bid: 0.005,
        available: true,
        time: 63019,
        ended: '',
        owner: 'Wolfram'
    },
    wm11114: {
        id: 4,
        image: '/res-img/item4.png',
        category: 'Collectibles',
        name: 'Digital art piece',
        current_bid: 2345,
        highest_bid: 0.005,
        available: true,
        time: 63019,
        ended: '',
        owner: 'Wolfram'
    },
    wm11115: {
        id: 5,
        image: '/res-img/item5.png',
        category: 'Collectibles',
        name: 'Digital art piece',
        current_bid: 2345,
        highest_bid: 0.005,
        available: true,
        ended: '',
        time: 16000,
        owner: 'Wolfram'
    },
    wm11116: {
        id: 6,
        image: '/res-img/item6.png',
        category: 'Collectibles',
        name: 'Digital art piece',
        current_bid: 2345,
        highest_bid: 0.005,
        available: true,
        time: 63019,
        ended: '',
        owner: 'Wolfram'
    },
    wm11117: {
        id: 7,
        image: '/res-img/item7.png',
        category: 'Collectibles',
        name: 'Digital art piece',
        current_bid: 2345,
        highest_bid: 0.005,
        available: false,
        time: 63019,
        ended: '',
        owner: 'Wolfram'
    },
    wm11118: {
        id: 8,
        image: '/res-img/item8.png',
        category: 'Collectibles',
        name: 'Digital art piece',
        current_bid: 2345,
        highest_bid: 0.005,
        available: false,
        time: 63019,
        ended: '',
        owner: 'Wolfram'
    },
    wm11119: {
        id: 9,
        image: '/res-img/item9.png',
        category: 'Collectibles',
        name: 'Digital art piece',
        current_bid: 2345,
        highest_bid: 0.005,
        available: false,
        time: 63019,
        ended: '',
        owner: 'Wolfram'
    },
    wm111110: {
        id: 10,
        image: '/res-img/item10.png',
        category: 'Collectibles',
        name: 'Digital art piece',
        current_bid: 2345,
        highest_bid: 0.005,
        available: false,
        time: 63019,
        ended: '',
        owner: 'Wolfram'
    },
    wm111111: {
        id: 11,
        image: '/res-img/item11.png',
        category: 'Collectibles',
        name: 'Digital art piece',
        current_bid: 2345,
        highest_bid: 0.005,
        available: false,
        time: 63019,
        ended: '',
        owner: 'Wolfram'
    },
    wm111112: {
        id: 12,
        image: '/res-img/item12.png',
        category: 'Collectibles',
        name: 'Digital art piece',
        current_bid: 2345,
        highest_bid: 0.005,
        available: false,
        time: 63019,
        ended: '',
        owner: 'Wolfram'
    }
};
